### ISSUE TITLE
Seperate Out Sprite Sheets

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/kcg#4]
All assets are being rendered from one tile sheet and texture

1> Create a file for enums for spritesheets (in library called constants)
- spritesheets.cs

- 0 is reserved and is error
- one sprites sheet id for or stars
- one sprite sheet id for particles

- one sprite sheet for background layers

- one sprite sheet for planet tiles (back, mid, front)

2> There must be a struct for SpriteSheet with 
- type of sheet, based upon enum
- the sheet id
- the pixel data in the sheet (array of RBGA), can be int32

3> There should be a SpriteSheetManager 
- maybe globals for sprite sheets 

4> Files should be in sprite-sheet folder

5> 
- planet-tiles on one sprite sheet (front, back, mid tiles)
- furniture on another sprite sheet 

6> API for copying sprites to sheet
- for example from loading tiles from png files

7> Make sure each stage of the map draw is separated
- a different sprite sheet for each layer
- a different mesh for each layer
- an enum describing each layer

**Comment by PavelTorgashov** [comment]
Done.
