### ISSUE TITLE
PlanetTileMap: Move SpriteId into TileProperty structs

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/kcg#9]
1> Currently the SpriteId is in the PlanetTile struct

2> Make and array of TileProperties structs
- one for Mid, Back, Foreground tiles
- so we can look these up by index/id from TileTypeId

3> Move the SpriteId into the TileProperties struct. Then we can look up this data from array.

4> Add a second sprite id to TileProperties struct. Just in case (for composited tiles, etc)

5> Add RenderMode enum. This is for normal rendering. Composited, etc. To add options for how this specific tile type would be rendered.

5>:
Question:
- Do We want one TileProperty struct for back/mid/front and just a type field for layer? I think one struct is probably OK.
- Do we want to just have a single array of TileProperties or three arrays (one for front, middle, back layer). I think one array is fine.
- Do we want to have three TileIds, one for front, middle, back layers or a single ID. I think a single ID is fine.

**Comment by kenje4090** [comment]
- only 1 array of TileProperties struct
- TileProperties Struct will have fields SpriteID, SecondSpriteID, RenderMode with enum 1-normal, 2-composited, etc, and TileTypeID with enum 1-mid, 2-back, 3-foreground

**Comment by PavelTorgashov** [comment]
Done.
